### ISSUE TITLE
Issues with pip dependency with this example 

### ISSUE THREAD

**Issue by ANicolucciTreeOfLife** [aws-samples/aws-sam-terraform-examples#1]
I'm trying to go use this example in order to deploy my lambda functions  using terraform with their python library dependencies. 

However, when following this example, I hit this error.

_null_resource.build_lambda_function (local-exec): pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling_

Is there a step that needs to be done to insure terraform has pip installed when it is deploying to aws? If so, where would this go in your examples?

**Comment by ANicolucciTreeOfLife** [comment]
after thinking this over a bit more....I think this can be resolved by just installing pip locally in your virtual environment or add pip install to github action.

**Comment by ElijahLynn** [comment]
Yeah, I hit an error with `pip` missing too, had to `apt install python3-pip` on my local for testing this out. Should be mentioned in the docs.
